#use proxy provided by https://github.com/ThekingMX1998/free-v2ray-code
#official config wiki: https://github.com/Dreamacro/clash/wiki/configuration
parser:
  type: 2
  destination: "../tmp/2.yml"
  date: "èŠ‚ç‚¹æ›´æ–°æ—¶é—´([\\d/\\_]+)"
  area: "(.*?)gf"
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
proxies:
  - use: 
    - https://raw.gitfast.tk/ThekingMX1998/free-v2ray-code/master/Subscription/Clash/GreenFishYYDS
    - https://raw.githubusercontent.com/ThekingMX1998/free-v2ray-code/master/Subscription/Clash/GreenFishYYDS
    rename:
      from: \(ç»¿å¤´å¤–ç½‘é›†å›¢\)\(Public\)
      to: gf
    info:
      date: èŠ‚ç‚¹æ›´æ–°æ—¶é—´([\\d/\\_]+)
proxy-groups:
  - name: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - use: all
  - name: ğŸ¥ NETFLIX
    type: select
    proxies:
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - use: all 
  - name: â›”ï¸ å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies:
      - ğŸ›‘ å…¨çƒæ‹¦æˆª
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
  - name: ğŸš« è¿è¥åŠ«æŒ
    type: select
    proxies:
      - ğŸ›‘ å…¨çƒæ‹¦æˆª
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
  - name: ğŸŒ å›½å¤–åª’ä½“
    type: select
    proxies:
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - use: all 
        filter: "gf"
  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - use: all 
        filter: "gf"
  - name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
    type: select
    proxies:
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - use: all 
        filter: "gf"
  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies:
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - use: all
        filter: "gf"
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT
  - name: ğŸ›‘ å…¨çƒæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - use: all
        filter: "gf"
rules:
  - use: 
    - https://raw.gitfast.tk/ThekingMX1998/free-v2ray-code/master/Subscription/Clash/GreenFishYYDS
    - https://raw.githubusercontent.com/ThekingMX1998/free-v2ray-code/master/Subscription/Clash/GreenFishYYDS
  - DOMAIN-SUFFIX,mathpix.com,ğŸ¯ å…¨çƒç›´è¿
  - DOMAIN-SUFFIX,jable.tv,ğŸ›‘ å…¨çƒæ‹¦æˆª
  - DOMAIN-SUFFIX,pornhub.com,ğŸš« è¿è¥åŠ«æŒ
  - DOMAIN-SUFFIX,telemetr.io,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
  - DOMAIN-SUFFIX,cdn.jsdelivr.net,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
  - DOMAIN-SUFFIX,regex101.com,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
  - DOMAIN-SUFFIX,npmjs.com,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
  - DOMAIN-SUFFIX,azureedge.net,ğŸ”° èŠ‚ç‚¹é€‰æ‹©